[advisories]
ignore = [
    #"RUSTSEC-0000-0000",
    { id = "RUSTSEC-2026-0009", reason = "`time` parsing functions not used by this crate" },
]

[licenses]
# List of explicitly allowed licenses
# See https://spdx.org/licenses/ for list of possible licenses
# [possible values: any SPDX 3.11 short identifier (+ optional exception)].
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-3.0"
    #"Apache-2.0 WITH LLVM-exception",
]
